# Generated by Django 3.2.7 on 2021-10-04 17:43

import custom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account',
            field=models.CharField(blank=True, default=custom.models.get_default_id, max_length=250, null=True),
        ),
    ]
